[package]
name = "remoc-pipelining-example"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
remoc = { path = "../../remoc" }

bytes = "1"
futures = "0.3"
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread", "sync", "time"] }
